# Generated by Django 6.0.1 on 2026-02-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_merge_20260225_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='down_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Down payment required', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='down_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='completed', help_text='Status of down payment', max_length=20),
        ),
    ]
