# Generated by Django 6.0.1 on 2026-02-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_order_down_payment_amount_order_down_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='down_payment_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='down_payment_status',
        ),
    ]
