# Generated by Django 6.0.1 on 2026-03-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_order_down_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, help_text='Requested delivery time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_name',
            field=models.CharField(blank=True, help_text='Name of delivery rider', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_phone',
            field=models.CharField(blank=True, help_text='Contact number of rider', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_vehicle',
            field=models.CharField(blank=True, help_text='Vehicle used for delivery (e.g. motorcycle, car)', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Name of person sending the order', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_phone',
            field=models.CharField(blank=True, help_text='Contact number of sender', max_length=20),
        ),
    ]
