# Generated by Django 6.0.1 on 2026-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_order_delivery_time_order_rider_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlySalesSnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
                ('calendar_data', models.JSONField(default=dict, help_text='Complete 12-month sales calendar data')),
                ('all_months_archive', models.JSONField(default=dict, help_text='Archive of all monthly sales')),
                ('total_yearly_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yearly Sales Snapshot',
                'verbose_name_plural': 'Yearly Sales Snapshots',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySalesArchive',
            fields=[
                ('archive_id', models.AutoField(primary_key=True, serialize=False)),
                ('month_name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('sales_by_day', models.JSONField(default=dict, help_text='Sales amounts by day {day: amount}')),
                ('orders_by_day', models.JSONField(default=dict, help_text='Order details by day {day: [order_data, ...]}')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monthly Sales Archive',
                'verbose_name_plural': 'Monthly Sales Archives',
                'ordering': ['-year', '-archive_id'],
                'unique_together': {('month_name', 'year')},
            },
        ),
    ]
