# Generated by Django 6.0.2 on 2026-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_monthly_cleanup_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.TextField(blank=True, help_text='Receiver address for this order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash_james', 'GCash - James'), ('gcash_banban', 'GCash - Banban'), ('gcash_kysan', 'GCash - Kysan'), ('rcbc', 'RCBC')], default='cash', max_length=20),
        ),
    ]
